import prisma from '@/lib/prisma';

// The Setting delegate is generated by `prisma generate` at build time. We access
// it through a narrow typed view so this file compiles even before generation.
type SettingRow = { key: string; value: string };
const settingDb = prisma as unknown as {
  setting: {
    findMany: () => Promise<SettingRow[]>;
    upsert: (args: {
      where: { key: string };
      update: { value: string };
      create: { key: string; value: string };
    }) => Promise<SettingRow>;
  };
};

// Keys the admin Settings page manages.
export const SETTING_KEYS = [
  'siteName',
  'siteDescription',
  'contactEmail',
  'contactPhone',
  'whatsappNumber',
  'address',
  'facebookUrl',
  'linkedinUrl',
  'instagramUrl',
  'youtubeUrl',
  'metaPixelId',
  'metaAccessToken',
  'gtmId',
  'ga4Id',
] as const;

export type SettingKey = (typeof SETTING_KEYS)[number];

/** Read all settings as a plain object. Missing keys are simply absent. */
export async function getAllSettings(): Promise<Record<string, string>> {
  try {
    const rows = await settingDb.setting.findMany();
    return Object.fromEntries(rows.map((r) => [r.key, r.value]));
  } catch {
    return {};
  }
}

/** Upsert a batch of settings. Only known keys are written. */
export async function saveSettings(values: Record<string, unknown>): Promise<void> {
  const entries = Object.entries(values).filter(
    ([k, v]) => (SETTING_KEYS as readonly string[]).includes(k) && v !== undefined && v !== null
  );
  await Promise.all(
    entries.map(([key, value]) =>
      settingDb.setting.upsert({
        where: { key },
        update: { value: String(value) },
        create: { key, value: String(value) },
      })
    )
  );
}

/**
 * Meta config: DB value takes precedence, environment variable is the fallback.
 * This lets the admin panel override env without a redeploy.
 */
export async function getMetaConfig(): Promise<{ pixelId: string | null; accessToken: string | null }> {
  const settings = await getAllSettings();
  const pixelId = settings.metaPixelId || process.env.NEXT_PUBLIC_META_PIXEL_ID || null;
  const accessToken = settings.metaAccessToken || process.env.META_ACCESS_TOKEN || null;
  return { pixelId, accessToken };
}

const clean = (v: string | undefined, ...placeholders: string[]) =>
  v && !placeholders.includes(v) ? v : null;

/**
 * Non-sensitive public tag IDs (Meta Pixel, GTM container, GA4). Safe to expose
 * to the browser. DB values take precedence over environment variables.
 */
export async function getPublicTagConfig(): Promise<{
  metaPixelId: string | null;
  gtmId: string | null;
  ga4Id: string | null;
}> {
  const s = await getAllSettings();
  return {
    metaPixelId: clean(s.metaPixelId || process.env.NEXT_PUBLIC_META_PIXEL_ID, '1234567890'),
    gtmId: clean(s.gtmId || process.env.NEXT_PUBLIC_GTM_ID, 'GTM-XXXXXXX'),
    ga4Id: clean(s.ga4Id || process.env.NEXT_PUBLIC_GA4_MEASUREMENT_ID, 'G-XXXXXXXXXX'),
  };
}
